# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---

project_name: kube-better-node

before:
  hooks:
    - go mod tidy

builds:
  - main: cmd/kube-better-node/main.go
    binary: kube-better-node
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
